spring.application.name=jwt-security-demo

spring.datasource.url=jdbc:postgresql://localhost:5432/jwt-security-demo
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

## jwt
security.jwt.private-key=classpath:certs/private.pem
security.jwt.public-key=classpath:certs/public.pem